apiVersion: v1
kind: Service
metadata:
  name: ums-backend-service
spec:
  selector:
    app: umsbackenddeploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

